server:
  port: 9412

---
spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/